Description: >
  Create API Gateway Rest API for the Fargate ECS Service

Parameters:
  ApiName:
    Type: String

  ApiDescription:
    Type: String

  ApiEndpointType:
    Type: String

  Path:
    Type: String

  StackName:
      Type: String

Resources:
  OctankAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: !Ref ApiDescription
      EndpointConfiguration:
        Types:
          - !Ref ApiEndpointType
      FailOnWarnings: true
      Name: !Ref ApiName
  
  ProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt OctankAPI.RootResourceId
      RestApiId: !Ref "OctankAPI"
      PathPart: '{proxy+}'

  RootResourceMethodGET:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref "OctankAPI"
      ResourceId: !GetAtt OctankAPI.RootResourceId 
      HttpMethod: GET      
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri:
          Fn::ImportValue:
            !Join [':', [!Ref 'StackName', 'ServiceUrl']]
        IntegrationResponses:
            - StatusCode: "200"
              ResponseParameters: 
                "method.response.header.Content-Type": "'text/html'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            "method.response.header.Content-Type": true

  ProxyMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref ProxyResource
      RestApiId: !Ref "OctankAPI"
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri:
          Fn::ImportValue:
            !Join [':', [!Ref 'StackName', 'ProxyUrl']]        
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200

  Deployment: 
    DependsOn: "RootResourceMethodGET"
    Type: "AWS::ApiGateway::Deployment"
    Properties: 
      RestApiId: !Ref "OctankAPI"
      Description: "Production Deployment"
      StageName: "Production"

Outputs:
  OctankAPI:
    Description: Name of the API.
    Value: !Ref OctankAPI
